package com.example.cornel.demo.statemachinenew;

public enum States2 {

    NOT_STARTED,
    FORK,JOIN,CHOICE,
    TASKS,CLONE1_START,CLONE1_END, PIPELINE1_START,PIPELINE1_END, VALIDATION1_START,VALIDATION1_END,
    CLONE2_START,CLONE2_END, PIPELINE2_START,PIPELINE2_END, VALIDATION2_START,VALIDATION2_END,
    ERROR,
    SCORE,
    END

//
//
//
//    READY,
//    FORK, JOIN, CHOICE,
//    TASKS, T1, T1E, T2, T2E, T3, T3E,
//    ERROR, AUTOMATIC, MANUAL,
//    NEXT1,NEXT2,END
}
