package com.example.cornel.demo.statemachine;

public enum States {

    NOT_STARTED,
    FORK, JOIN, CHOICE,
    CHOICE_PIPELINE1_CREATE,CHOICE_PIPELINE1_RUN,
    CHOICE_PIPELINE2_CREATE,CHOICE_PIPELINE2_RUN,
    TASKS,
    CLONE1, PIPELINE1_CREATE,PIPELINE1_RUN, PIPELINE1_METRICS, TASKS1_DONE,
    CLONE2, PIPELINE2_CREATE,PIPELINE2_RUN, PIPELINE2_METRICS, TASKS2_DONE,
    ERROR,
    SCORE,
    END

}
